# Stage 1: Base image for installing dependencies
FROM node:20.10.0-alpine3.18 AS base
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install

# Stage 2: Development stage
FROM base as dev
COPY . .
CMD ["npm", "run", "start"]

