version: "3.8"
services:

  # Development service
  development:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"

  # Production service
  production:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
