version: "3.8"

services:
  front-end: 
    build:
      context: studdybuddy'
      dockerfile: Dockerfile
    container_name: front-end
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
      - ./dist:/app/dist
      

